patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "anddea/revanced-cli"
rv-brand = "ReX"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding name YouTube'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
included-patches = "'Custom branding name YouTube Music'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
included-patches = "'Change package name' 'Custom branding name Reddit'"




